// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzpbfylaimdgdmchxxzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cGJmeWxhaW1kZ2RtY2h4eHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0OTkwNTYsImV4cCI6MjA1NDA3NTA1Nn0.tZyT5VnQNFMODvYaTTcVOcPK5qzd5U8slGODem5nER8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);